modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="basemod"
version="1.0.0"
displayName="Base Mod"
authors="Minetrigg3r"
description='''
Base mod for other mods
'''

[[dependencies.basemod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.basemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH" 